title: hcornelison.dev blog
locale: "en-US"

#comment out while debugging locally
baseurl: "https://blog.hcornelison.dev"

#uncomment for local debugging!
#baseurl: "" 

url: https://blog.hcornelison.dev
repository: "https://github.com/hcornelison/blog"
email: me@hcornelison.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: hcornelison
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "hcornelison"
  avatar : https://avatars.githubusercontent.com/u/34791049?s=400&u=e2451076951e95554c8e9fb1828ce8bbc805b000&v=4
  bio    : "My awesome biography constrained to a sentence or two should have went here."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:me@hcornelison.dev"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://hcornelison.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hcornelison"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hcornelison"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/
